name: Build

# This Workflow Will Be Triggered Automatically

on: [push, pull_request]

jobs:

  # Build Library
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Config JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.3.6528147" --sdk_root=${ANDROID_SDK_ROOT}
    - name: Make gradlew Executable
      run: chmod +x ./gradlew
    - name: Execute Build
      run: ./gradlew :TeamCode:assembleDebug
